import { useEffect, useRef } from 'react'
import { Renderer, Program, Mesh, Triangle } from 'ogl'
import './Grainient.css'

const hexToRgb=hex=>{const m=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);return m?[parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255]:[1,1,1]}
const vertex=`#version 300 es
in vec2 position;void main(){gl_Position=vec4(position,0.,1.);}`
const fragment=`#version 300 es
precision highp float;uniform vec2 iResolution;uniform float iTime,uTimeSpeed,uColorBalance,uWarpStrength,uWarpFrequency,uWarpSpeed,uWarpAmplitude,uBlendAngle,uBlendSoftness,uRotationAmount,uNoiseScale,uGrainAmount,uGrainScale,uGrainAnimated,uContrast,uGamma,uSaturation,uZoom;uniform vec2 uCenterOffset;uniform vec3 uColor1,uColor2,uColor3;out vec4 fragColor;
#define S(a,b,t) smoothstep(a,b,t)
mat2 Rot(float a){float s=sin(a),c=cos(a);return mat2(c,-s,s,c);}vec2 hash(vec2 p){p=vec2(dot(p,vec2(2127.1,81.17)),dot(p,vec2(1269.5,283.37)));return fract(sin(p)*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p),u=f*f*(3.-2.*f);return .5+.5*mix(mix(dot(-1.+2.*hash(i),f),dot(-1.+2.*hash(i+vec2(1,0)),f-vec2(1,0)),u.x),mix(dot(-1.+2.*hash(i+vec2(0,1)),f-vec2(0,1)),dot(-1.+2.*hash(i+vec2(1,1)),f-vec2(1,1)),u.x),u.y);}
void main(){float t=iTime*uTimeSpeed;vec2 uv=gl_FragCoord.xy/iResolution.xy;float ratio=iResolution.x/iResolution.y;vec2 tuv=(uv-.5+uCenterOffset)/max(uZoom,.001);float d=noise(vec2(t*.1,tuv.x*tuv.y)*uNoiseScale);tuv.y/=ratio;tuv*=Rot(radians((d-.5)*uRotationAmount+180.));tuv.y*=ratio;float a=uWarpAmplitude/max(uWarpStrength,.001),wt=t*uWarpSpeed;tuv.x+=sin(tuv.y*uWarpFrequency+wt)/a;tuv.y+=sin(tuv.x*(uWarpFrequency*1.5)+wt)/(a*.5);float b=uColorBalance,s=max(uBlendSoftness,0.),x=(tuv*Rot(radians(uBlendAngle))).x,e0=-.3-b-s,e1=.2-b+s;vec3 l1=mix(uColor3,uColor2,S(e0,e1,x)),l2=mix(uColor2,uColor1,S(e0,e1,x)),col=mix(l1,l2,S(.5-b+s,-.3-b-s,tuv.y));vec2 guv=uv*max(uGrainScale,.001);if(uGrainAnimated>.5)guv+=vec2(iTime*.05);float g=fract(sin(dot(guv,vec2(12.9898,78.233)))*43758.5453);col+=(g-.5)*uGrainAmount;col=(col-.5)*uContrast+.5;float l=dot(col,vec3(.2126,.7152,.0722));col=mix(vec3(l),col,uSaturation);col=pow(max(col,0.),vec3(1./max(uGamma,.001)));fragColor=vec4(clamp(col,0.,1.),1.);}`
const ctxMap=new WeakMap()
export default function Grainient({color1='#081B35',color2='#527A91',color3='#D8A071',timeSpeed=.28,colorBalance=0,warpStrength=.75,warpFrequency=4.1,warpSpeed=1.1,warpAmplitude=55,blendAngle=0,blendSoftness=.12,rotationAmount=360,noiseScale=1.7,grainAmount=.035,grainScale=2,grainAnimated=false,contrast=1.12,gamma=1,saturation=.92,centerX=.06,centerY=0,zoom=.9,className=''}){
 const ref=useRef(null)
 useEffect(()=>{const c=ref.current;if(!c)return;const renderer=new Renderer({webgl:2,alpha:true,antialias:false,dpr:Math.min(devicePixelRatio||1,2)}),gl=renderer.gl,canvas=gl.canvas;Object.assign(canvas.style,{width:'100%',height:'100%',display:'block'});c.appendChild(canvas);const uniforms={};['iTime','uTimeSpeed','uColorBalance','uWarpStrength','uWarpFrequency','uWarpSpeed','uWarpAmplitude','uBlendAngle','uBlendSoftness','uRotationAmount','uNoiseScale','uGrainAmount','uGrainScale','uGrainAnimated','uContrast','uGamma','uSaturation','uZoom'].forEach(k=>uniforms[k]={value:0});uniforms.iResolution={value:new Float32Array([1,1])};uniforms.uCenterOffset={value:new Float32Array([0,0])};uniforms.uColor1={value:new Float32Array([1,1,1])};uniforms.uColor2={value:new Float32Array([1,1,1])};uniforms.uColor3={value:new Float32Array([1,1,1])};const program=new Program(gl,{vertex,fragment,uniforms}),mesh=new Mesh(gl,{geometry:new Triangle(gl),program});ctxMap.set(c,{program});const size=()=>{const r=c.getBoundingClientRect();renderer.setSize(Math.max(1,r.width|0),Math.max(1,r.height|0));program.uniforms.iResolution.value.set([gl.drawingBufferWidth,gl.drawingBufferHeight])};const ro=new ResizeObserver(size);ro.observe(c);size();let raf=0,start=performance.now(),visible=true,pageVisible=!document.hidden;const loop=t=>{program.uniforms.iTime.value=(t-start)*.001;renderer.render({scene:mesh});raf=requestAnimationFrame(loop)},sync=()=>{if(visible&&pageVisible&&!raf)raf=requestAnimationFrame(loop);else if((!visible||!pageVisible)&&raf){cancelAnimationFrame(raf);raf=0}};const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;sync()});io.observe(c);const onVis=()=>{pageVisible=!document.hidden;sync()};document.addEventListener('visibilitychange',onVis);sync();return()=>{if(raf)cancelAnimationFrame(raf);ro.disconnect();io.disconnect();document.removeEventListener('visibilitychange',onVis);ctxMap.delete(c);canvas.remove()}},[])
 useEffect(()=>{const x=ctxMap.get(ref.current);if(!x)return;const u=x.program.uniforms,vals={uTimeSpeed:timeSpeed,uColorBalance:colorBalance,uWarpStrength:warpStrength,uWarpFrequency:warpFrequency,uWarpSpeed:warpSpeed,uWarpAmplitude:warpAmplitude,uBlendAngle:blendAngle,uBlendSoftness:blendSoftness,uRotationAmount:rotationAmount,uNoiseScale:noiseScale,uGrainAmount:grainAmount,uGrainScale:grainScale,uGrainAnimated:grainAnimated?1:0,uContrast:contrast,uGamma:gamma,uSaturation:saturation,uZoom:zoom};Object.entries(vals).forEach(([k,v])=>u[k].value=v);u.uCenterOffset.value.set([centerX,centerY]);u.uColor1.value.set(hexToRgb(color1));u.uColor2.value.set(hexToRgb(color2));u.uColor3.value.set(hexToRgb(color3))},[timeSpeed,colorBalance,warpStrength,warpFrequency,warpSpeed,warpAmplitude,blendAngle,blendSoftness,rotationAmount,noiseScale,grainAmount,grainScale,grainAnimated,contrast,gamma,saturation,centerX,centerY,zoom,color1,color2,color3])
 return <div ref={ref} className={`grainient-container ${className}`.trim()}/>
}
